force-app/main/default/objects/Account/fields/DNI__c.field-meta.xml
<CustomField>
    <fullName>DNI__c</fullName>
    <description>DNI del cliente</description>
    <externalId>true</externalId>
    <label>DNI</label>
    <length>10</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Detalle_Factura__c/Detalle_Factura__c.object-meta.xml
<CustomObject>
    <label>Detalle Factura</label>
    <nameField>
        <label>Detalle Factura Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Detalles factura</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Detalle_Factura__c/fields/Factura__c.field-meta.xml
<CustomField>
    <fullName>Factura__c</fullName>
    <label>Factura</label>
    <referenceTo>Factura__c</referenceTo>
    <relationshipLabel>Detalles factura</relationshipLabel>
    <relationshipName>Detalles_factura</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Detalle_Factura__c/fields/Precio_unitario__c.field-meta.xml
<CustomField>
    <fullName>Precio_unitario__c</fullName>
    <label>Precio unitario</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Factura__c/Factura__c.object-meta.xml
<CustomObject>
    <description>Objeto padre de facturas</description>
    <label>Factura</label>
    <nameField>
        <label>Factura Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Facturas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Factura__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Facturas</relationshipLabel>
    <relationshipName>Facturas</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Factura__c/fields/DNI__c.field-meta.xml
<CustomField>
    <fullName>DNI__c</fullName>
    <label>DNI</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/handlerDetalleFactura.cls
public with sharing class handlerDetalleFactura 
{
   
    public static void insertTrigger(list<Detalle_Factura__c> lstDetFactura) 
    {
        list<Account> clientes = new List<Account>();
        list<Factura__c> facturas = new List<Factura__c>();
        Set<Id> idFactura = new Set<Id>(); 
        Set<String> idCliente = new Set<string>();
        map<String, Factura__c> mapFactura = new map<String, Factura__c>();
        map<String, Account> mapAccount = new map<String, Account>();

        for(Detalle_Factura__c detFactura : lstDetFactura)
        {
            if(detFactura.Factura__c != null)
            {
                idFactura.add(detFactura.Factura__c);
            }
            if(detFactura.Cantidad__c > 0 && detFactura.Precio_unitario__c > 0)
            {
                detFactura.Precio__c = detFactura.Cantidad__c * detFactura.Precio_unitario__c;
            }else
            {
                if(detFactura.Cantidad__c <= 0)
                {
                    detFactura.Cantidad__c.addError('La cantidad tiene que ser mayor a 0! el valor actual es: '+detFactura.Cantidad__c);
                }   
                if(detFactura.Precio_unitario__c <= 0)
                {
                    detFactura.Precio_unitario__c.addError('El precio tiene que ser mayor a 0! el valor actual es: '+detFactura.Precio_unitario__c);
                }    
            }  
        }

        facturas = [Select id, Account__c, DNI__c From Factura__c Where id IN :idFactura];

        for(Factura__c factura : facturas)
        {
            if(factura.DNI__c != null)
            {
                mapFactura.put(factura.DNI__c, factura);
            }
        }

        for(Account cliente : [Select Id, DNI__c From Account Where DNI__c IN :mapFactura.keySet()])
        {
            mapAccount.put(cliente.DNI__c, cliente);
        }

        for(Factura__c factura : facturas)
        {
           if(mapAccount.containsKey(factura.DNI__c))
           {
               factura.Account__c = mapAccount.get(factura.DNI__c).id;
           }
        }
        update facturas;
    
    }

    public static void upadteTrigger(list<Detalle_Factura__c> lstDetFactura)
    {
        for(Detalle_Factura__c detFactura : lstDetFactura)
        {
            if(detFactura.Cantidad__c > 0 && detFactura.Precio_unitario__c > 0)
            {
                detFactura.Precio__c = detFactura.Cantidad__c * detFactura.Precio_unitario__c;
            }
        } 
    }
}